name: Yodeai Tests
on: 
  workflow_dispatch:
  push:
jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v2
      uses: actions/setup-node@v1
        with:
          node-version: "20.2.4"
      run: pnpm install
      run: pnpm test
