name: Yodeai Tests

on:
  workflow_dispatch:
  push:

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js and install pnpm
        uses: actions/setup-node@v1
        with:
          node-version: "18.17.1"
      - run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test
